Traceback (most recent call last):
  File "/opt/oracle/upapi/insert_data.py", line 1, in <module>
    import pyodbc
ModuleNotFoundError: No module named 'pyodbc'
Traceback (most recent call last):
  File "/opt/oracle/upapi/insert_data.py", line 1, in <module>
    import pyodbc
ModuleNotFoundError: No module named 'pyodbc'
Traceback (most recent call last):
  File "/opt/oracle/upapi/insert_data.py", line 1, in <module>
    import pyodbc
ModuleNotFoundError: No module named 'pyodbc'
Traceback (most recent call last):
  File "/opt/oracle/upapi/insert_data.py", line 1, in <module>
    import pyodbc
ModuleNotFoundError: No module named 'pyodbc'
